version: '3.4'
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.33.0.0/16
services:
    wifi.public.dappnode.eth:
        image: 'wifi.dnp.dappnode.eth:0.0.1'
        build: ./build
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        dns: 172.33.1.2
        privileged: true
        restart: always
        networks:
            network:
                ipv4_address: 172.33.1.10
